# documentation and
# starship configuration: https://starship.rs/config/
#
command_timeout = 5000

[battery]
disabled = true

[nodejs]
format = "via [node.js ($version )]($style)"
disabled = true

[python]
python_binary = "python3"
disabled = true

[shell]
bash_indicator = "bash "
disabled = false
format = "[$indicator]($style)"
style = "cyan bold"
unknown_indicator = "??? "
zsh_indicator = ""

[hg_branch]
#truncation_length = 36
truncation_symbol = '…'
disabled = false
