# documentation and
# starship configuration: https://starship.rs/config/
#
command_timeout = 5000

[battery]
disabled = true

[nodejs]
disabled = true
format = "via [node.js ($version )]($style)"

[python]
disabled = true
python_binary = "python3"

[shell]
bash_indicator = "bash "
disabled = false
format = "[$indicator]($style)"
style = "cyan bold"
unknown_indicator = "??? "
zsh_indicator = ""

[hg_branch]
#truncation_length = 36
disabled = false
truncation_symbol = '…'
